### ISSUE TITLE
Add 2FA (two step verification)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#489] opened 2022-02-15 19:25 UTC
As a user I want to be able to use 2FA.

Acceptance Criteria:
 - [ ] It should be possible to use appls like Google Authentificatior

Note: this task is low prio because the majority of uses do not use 2FA yet and if they use it they only use it where they have to.
I would make this this task only high-prio if we force 2FA.

**Comment by sarahsporck** [comment] 2023-10-16 13:19
maybe we should start with 2fa via email. Check back with the cms team, as they already use 2FA.

**Comment by sarahsporck** [comment] 2024-02-06 10:19
This is a duplicate of #1217 therefore I'll close this issue.

**Closed by sarahsporck** 2024-02-06 10:19 UTC
Labels: user story, low prio
